#=
Publish a coverage run as documentation: docs/COVERAGE.md (the funnel, per domain, what stops
the failing models, the models that simulate but do not validate) and the "Latest coverage"
section of README.md (between its coverage markers).

    julia --project=. scripts/publish_coverage.jl <results.jls> [commits.txt] [note]

<results.jls> is a serialized Vector{ModelResult}: the partial_*.jls of scripts/run_full_coverage.jl,
or results_noskip.jls of a no-skip run (every model through every phase, the registry's skips
removed). [commits.txt] lists "<repository> <commit>" lines, one per package, as recorded when the
run started; [note] is one line on how the run was made (e.g. "no-skip, 3 workers, 600 s per model").
=#

using Dates
using Printf
using Serialization

import OMLibraryTesting
const OLT = OMLibraryTesting

length(ARGS) >= 1 || error("usage: publish_coverage.jl <results.jls> [commits.txt] [note]")
const RESULTS = deserialize(ARGS[1])::Vector{OMLibraryTesting.ModelResult}
const COMMITS = length(ARGS) >= 2 && isfile(ARGS[2]) ?
    [String.(split(l)) for l in eachline(ARGS[2]) if occursin(r"^\S+\.jl \S+$|^OM\.jl \S+$", l)] : Vector{String}[]
const NOTE = length(ARGS) >= 3 ? ARGS[3] : ""
const ROOT = joinpath(@__DIR__, "..") |> abspath
const MEASURED = Dates.format(Dates.unix2datetime(mtime(ARGS[1])), "yyyy-mm-dd")

ok(r) = r.highest != OLT.BROKEN && r.highest != OLT.UNKNOWN
reached(r, p) = ok(r) && r.highest >= p
domainOf(r) = join(split(r.spec.domain, '.')[1:min(2, end)], '.')
short(name) = replace(name, "Modelica." => "")
function firstError(r)
    local failed = [pr for pr in r.phases if !pr.success]
    return isempty(failed) ? "" : something(first(failed).error, "")
end
#= The first line of an error with names and numbers blanked, so similar failures group together. =#
function errorClass(e)
    local s = replace(first(split(e, '\n')), r"\s+" => " ")
    s = replace(s, r"`[^`]*`" => "`…`", r"\"[^\"]*\"" => "\"…\"", r"[0-9]+(\.[0-9]+)?(e[-+]?[0-9]+)?" => "N")
    return first(s, 90)
end
mdcell(s) = replace(s, "|" => "\\|")

const N = length(RESULTS)
const FUNNEL = [(OLT.PHASE_NAMES[p], count(r -> reached(r, p), RESULTS)) for p in (OLT.FRONTEND, OLT.BACKEND, OLT.SIMULATE, OLT.VALIDATE)]
pct(n) = @sprintf("%.1f %%", 100n / N)

function write_coverage(io)
    println(io, "# MSL coverage of OM.jl\n")
    println(io, "Measured $MEASURED: $N example models of the Modelica Standard Library, each run through OM.jl's ",
            "pipeline (flatten, translate, simulate) and validated against the reference trajectories.",
            isempty(NOTE) ? "" : " $NOTE.", "\n")
    if !isempty(COMMITS)
        println(io, "Commits: ", join(("$(c[1]) `$(c[2])`" for c in COMMITS), ", "), ".\n")
    end
    println(io, "Generated by `scripts/publish_coverage.jl` from the run's results; do not edit by hand.\n")
    println(io, "## Summary\n")
    println(io, "| Phase reached | Models | Share |\n|---|---|---|")
    foreach(((p, c),) -> println(io, "| $p | $c | $(pct(c)) |"), FUNNEL)
    println(io, "| total | $N | |\n")
    println(io, "## Per domain\n")
    println(io, "| Domain | Models | Validate | Simulate only | Backend only | Frontend only | None |\n|---|---|---|---|---|---|---|")
    for d in sort(unique(domainOf.(RESULTS)))
        local rs = filter(r -> domainOf(r) == d, RESULTS)
        local v = count(r -> reached(r, OLT.VALIDATE), rs)
        local s = count(r -> ok(r) && r.highest == OLT.SIMULATE, rs)
        local b = count(r -> ok(r) && r.highest == OLT.BACKEND, rs)
        local f = count(r -> ok(r) && r.highest == OLT.FRONTEND, rs)
        println(io, "| $(short(d)) | $(length(rs)) | $v | $s | $b | $f | $(length(rs) - v - s - b - f) |")
    end
    println(io, "\n## What stops the models that do not validate\n")
    println(io, "Grouped by the last phase a model reached and its first error (names and numbers blanked).\n")
    local classes = Dict{Tuple{String, String}, Vector{String}}()
    for r in filter(r -> !reached(r, OLT.VALIDATE), RESULTS)
        local stop = ok(r) ? OLT.PHASE_NAMES[r.highest] : "none"
        push!(get!(classes, (stop, errorClass(firstError(r))), String[]), r.spec.name)
    end
    println(io, "| Stops after | Models | First error | Examples |\n|---|---|---|---|")
    for ((stop, cls), ms) in sort(collect(classes); by = x -> (-length(x[2]), x[1]))
        println(io, "| $stop | $(length(ms)) | $(mdcell(cls)) | $(join(first(short.(sort(ms)), 2), ", ")) |")
    end
    println(io, "\n## Models that simulate but do not validate\n")
    for r in sort(filter(r -> ok(r) && r.highest == OLT.SIMULATE, RESULTS); by = r -> r.spec.name)
        println(io, "- ", short(r.spec.name), ": ", mdcell(first(replace(firstError(r), '\n' => ' '), 110)))
    end
end

mkpath(joinpath(ROOT, "docs"))
open(write_coverage, joinpath(ROOT, "docs", "COVERAGE.md"), "w")

#= The README's section between the markers: the headline numbers and a link. =#
const BEGIN_MARK = "<!-- coverage:begin (scripts/publish_coverage.jl) -->"
const END_MARK = "<!-- coverage:end -->"
const readme_path = joinpath(ROOT, "README.md")
const readme = read(readme_path, String)
const section = string(BEGIN_MARK, "\n",
    "Measured $MEASURED on $N MSL example models: ",
    join(("$(lowercase(p)) $c ($(pct(c)))" for (p, c) in FUNNEL), ", "),
    ". Per domain and what stops the rest: [docs/COVERAGE.md](docs/COVERAGE.md).\n", END_MARK)
occursin(BEGIN_MARK, readme) || error("README.md has no coverage markers ($BEGIN_MARK … $END_MARK)")
write(readme_path, replace(readme, Regex("\\Q$BEGIN_MARK\\E.*?\\Q$END_MARK\\E", "s") => section))
@info "Published" coverage = joinpath(ROOT, "docs", "COVERAGE.md") funnel = FUNNEL
